default: &default
 familyids:
  - 126
  - 64
  - 63
  - 53
  - 52
  # - 23
  # - 24
  # - 35
  # - 36

 notrump:
  - Weak
  - Strong
  - Var

 system:
  - 5CM
  - Acol

development:
  <<: *default

test:
  <<: *default

production:
 <<: *default
 familyids:
  - 52
  - 53
  - 63
  - 64
  - 126
